[package]
name = "surfacelab"
version = "0.1.0"
authors = ["Paul Ogris <paul@tsahyt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiqueue2 = "0.1.6"
env_logger = "0.7.1"
log = "0.4.8"
gtk = { version = "0.8.1", path = "../gtk-rs/gtk" }
gtk-sys = { git = "https://github.com/gtk-rs/sys" }
gdk = { git = "https://github.com/gtk-rs/gdk", features = ["v3_20"] }
gdk-sys = { git = "https://github.com/gtk-rs/sys" }
gio = { git = "https://github.com/gtk-rs/gio" }
glib = { git = "https://github.com/gtk-rs/glib" }
glib-sys = { git = "https://github.com/gtk-rs/sys" }
petgraph = "0.5.0"
maplit = "1.0.2"
cairo-rs = { git = "https://github.com/gtk-rs/cairo" }
