[package]
name = "surfacelab"
version = "0.1.0"
authors = ["Paul Ogris <paul@tsahyt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiqueue2 = "0.1.6"
env_logger = "0.7.1"
log = "0.4.8"
gtk = "0.8.0"
gdk = "0.12.0"
gio = "0.8.0"
petgraph = "0.5.0"
maplit = "1.0.2"
