#version 460

layout(local_size_x = 1, local_size_y = 1) in;

// layout(set = 0, binding = 0) uniform Params {
// };
layout(set = 0, binding = 1) uniform texture2D t_Color1;
layout(set = 0, binding = 2) uniform sampler Sampler;
layout(set = 0, binding = 3, rgba16f) uniform image2D t_Out;

void main() {
    ivec2 idx = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
    vec2 uv = vec2(idx.x / 1024., idx.y / 1024.);
    imageStore(t_Out, idx, vec4(0.));
}
